server:
  port: 8081
  error:
    include-message: always
    include-binding-errors: always
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: user
    password: telegramDb
  jpa:
    hibernate:
      ddl-auto: update
    show_sql: true
    properties:
      hibernate:
      format_sql: true
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQL95Dialect

telegram:
  bot:
    username: "@UParse_Bot"
    url: "https://api.telegram.org/"
    webhook-path: "https://7f43-5-16-118-81.ngrok-free.app/"
    token: "INSERT YOUR BOT CODE"