server:
  port: 8081
  error:
    include-message: always
    include-binding-errors: always
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: user
    password: telegramDb
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    show_sql: true
    properties:
      hibernate:
      format_sql: true
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQL95Dialect

telegram:
  bot:
    username: "@DataHarvest_Bot"
    url: "https://api.telegram.org/"
    webhook-path: "https://192f-5-16-118-81.ngrok-free.app"
    path-for-messages: "https://192f-5-16-118-81.ngrok-free.app/send"
    token: "6092572923:AAFJaAXaR_K5h_fkqGr6TSNPmSFBjBrciBg"